Comment ui-test-result job

diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -475,27 +475,27 @@ jobs:
   #         path: app/client/cypress/screenshots/
 
   # ui-test-result:
-    needs: ui-test
-    if: always()
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - run: echo "All ui-test matrices completed"
+    # needs: ui-test
+    # if: always()
+    # runs-on: ubuntu-latest
+    # defaults:
+    #   run:
+    #     shell: bash
+    # steps:
+    #   - run: echo "All ui-test matrices completed"
 
-      - name: Return status for ui-matrix
-        run: |
-          if [[ "${{ needs.ui-test.result }}" == "success" ]]; then
-            echo "Integration tests completed successfully!";
-            exit 0;
-          elif [[ "${{ needs.ui-test.result }}" == "skipped" ]]; then
-            echo "Integration tests were skipped";
-            exit 1;
-          else
-            echo "Integration tests have failed";
-            exit 1;
-          fi
+    #   - name: Return status for ui-matrix
+    #     run: |
+    #       if [[ "${{ needs.ui-test.result }}" == "success" ]]; then
+    #         echo "Integration tests completed successfully!";
+    #         exit 0;
+    #       elif [[ "${{ needs.ui-test.result }}" == "skipped" ]]; then
+    #         echo "Integration tests were skipped";
+    #         exit 1;
+    #       else
+    #         echo "Integration tests have failed";
+    #         exit 1;
+    #       fi
 
   package:
     # needs: ui-test
